{% set name = "Ragna" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Ragna-{{ version }}.tar.gz
  sha256: d62cab74fdb9d90c870466f0243e6549cb7d6fe0cd0b8428058c6f661d4c8cb4
build:
  noarch: python
  entry_points:
    - ragna = ragna.__main__:app
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=45
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - aiofiles
    - emoji
    - fastapi
    - httpx
    - importlib-metadata >=4.6
    - packaging
    - panel ==1.3.8
    - pydantic >=2
    - pydantic-core
    - pydantic-settings >=2
    - pyjwt
    - python-multipart
    - redis-py
    - questionary
    - rich
    - sqlalchemy >=2
    - starlette
    - tomlkit
    - typer
    - uvicorn

test:
  imports:
    - ragna
  commands:
    - pip check
    - ragna --help
  requires:
    - pip

about:
  home: https://ragna.chat/
  summary: RAG orchestration framework
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kklein
